# Generated by Django 5.2.7 on 2025-10-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва події')),
                ('description', models.TextField(verbose_name='Опис події')),
                ('date', models.DateField(verbose_name='Дата проведення')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Час проведення')),
                ('location', models.CharField(max_length=200, verbose_name='Локація')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Зображення')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Подія',
                'verbose_name_plural': 'Події',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва організації')),
                ('description', models.TextField(verbose_name='Опис')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('image', models.ImageField(blank=True, null=True, upload_to='info/', verbose_name='Логотип')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показувати на сайті')),
            ],
            options={
                'verbose_name': 'Загальна інформація',
                'verbose_name_plural': 'Загальна інформація',
            },
        ),
    ]
