# Generated by Django 5.2.7 on 2025-10-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Їжа'), ('drink', 'Напій')], max_length=50, verbose_name='Категорія')),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True, verbose_name="Підкатегорія (напр. 'Кава', 'Бургери')")),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('weight_grams', models.IntegerField(blank=True, null=True, verbose_name='Вага (грами)')),
                ('volume_ml', models.IntegerField(blank=True, null=True, verbose_name="Об'єм (мл)")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
            ],
            options={
                'verbose_name': 'Позиція меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва фільму')),
                ('date', models.DateField(verbose_name='Дата показу')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Час початку показу')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies/', verbose_name='Постер')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Локація')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показувати на сайті')),
            ],
            options={
                'verbose_name': 'Фільм',
                'verbose_name_plural': 'Фільми',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
